# Generated by Django 5.2.11 on 2026-02-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0002_user_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True)),
                ('is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
    ]
