# Generated by Django 5.2.11 on 2026-02-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0003_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='is_archive',
            new_name='is_archived',
        ),
    ]
