# Generated by Django 5.2.11 on 2026-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0004_rename_is_archive_subjects_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='is_archived',
            new_name='is_archive',
        ),
    ]
