# Generated by Django 5.2.11 on 2026-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0005_rename_is_archived_subjects_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('subjects', models.ManyToManyField(blank=True, to='class_management.subjects')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
