# Generated by Django 5.2.11 on 2026-02-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0006_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='class_management.subjects'),
        ),
    ]
