# Generated by Django 5.2.11 on 2026-02-11 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0008_batches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='class_management.batches')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_subjects', to='class_management.subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_teacher',
            },
        ),
    ]
