# Generated by Django 5.2.11 on 2026-02-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0009_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_teacher',
            old_name='user',
            new_name='teacher',
        ),
    ]
